<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SudaneseCitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            // Khartoum State (1)
            [
                'name_ar' => 'الخرطوم',
                'name_en' => 'Khartoum',
                'state_id' => 1,
                'state_name_ar' => 'ولاية الخرطوم',
                'state_name_en' => 'Khartoum State',
                'latitude' => 15.5007,
                'longitude' => 32.5599,
                'is_major_city' => true,
                'has_airport' => true,
                'has_port' => false,
                'population' => 5274321,
                'active' => true
            ],
            [
                'name_ar' => 'أم درمان',
                'name_en' => 'Omdurman',
                'state_id' => 1,
                'state_name_ar' => 'ولاية الخرطوم',
                'state_name_en' => 'Khartoum State',
                'latitude' => 15.6446,
                'longitude' => 32.4777,
                'is_major_city' => true,
                'has_airport' => false,
                'has_port' => false,
                'population' => 2395159,
                'active' => true
            ],
            [
                'name_ar' => 'الخرطوم بحري',
                'name_en' => 'Khartoum North',
                'state_id' => 1,
                'state_name_ar' => 'ولاية الخرطوم',
                'state_name_en' => 'Khartoum State',
                'latitude' => 15.6031,
                'longitude' => 32.5265,
                'is_major_city' => true,
                'has_airport' => false,
                'has_port' => false,
                'population' => 1012211,
                'active' => true
            ],
            [
                'name_ar' => 'شرق النيل',
                'name_en' => 'Sharq An-Neel',
                'state_id' => 1,
                'state_name_ar' => 'ولاية الخرطوم',
                'state_name_en' => 'Khartoum State',
                'latitude' => 15.5500,
                'longitude' => 32.6000,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 500000,
                'active' => true
            ],

            // Red Sea State (2)
            [
                'name_ar' => 'بورتسودان',
                'name_en' => 'Port Sudan',
                'state_id' => 2,
                'state_name_ar' => 'ولاية البحر الأحمر',
                'state_name_en' => 'Red Sea State',
                'latitude' => 19.6158,
                'longitude' => 37.2164,
                'is_major_city' => true,
                'has_airport' => true,
                'has_port' => true,
                'population' => 489725,
                'active' => true
            ],
            [
                'name_ar' => 'سواكن',
                'name_en' => 'Suakin',
                'state_id' => 2,
                'state_name_ar' => 'ولاية البحر الأحمر',
                'state_name_en' => 'Red Sea State',
                'latitude' => 19.1076,
                'longitude' => 37.3321,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => true,
                'population' => 43337,
                'active' => true
            ],
            [
                'name_ar' => 'طوكر',
                'name_en' => 'Tokar',
                'state_id' => 2,
                'state_name_ar' => 'ولاية البحر الأحمر',
                'state_name_en' => 'Red Sea State',
                'latitude' => 18.4255,
                'longitude' => 37.7292,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 52000,
                'active' => true
            ],
            [
                'name_ar' => 'سنكات',
                'name_en' => 'Sinkat',
                'state_id' => 2,
                'state_name_ar' => 'ولاية البحر الأحمر',
                'state_name_en' => 'Red Sea State',
                'latitude' => 18.8012,
                'longitude' => 36.9869,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 25000,
                'active' => true
            ],
            [
                'name_ar' => 'حلايب',
                'name_en' => 'Halaib',
                'state_id' => 2,
                'state_name_ar' => 'ولاية البحر الأحمر',
                'state_name_en' => 'Red Sea State',
                'latitude' => 22.2167,
                'longitude' => 36.6333,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 10000,
                'active' => true
            ],

            // Kassala State (3)
            [
                'name_ar' => 'كسلا',
                'name_en' => 'Kassala',
                'state_id' => 3,
                'state_name_ar' => 'ولاية كسلا',
                'state_name_en' => 'Kassala State',
                'latitude' => 15.4542,
                'longitude' => 36.3999,
                'is_major_city' => true,
                'has_airport' => true,
                'has_port' => false,
                'population' => 419030,
                'active' => true
            ],
            [
                'name_ar' => 'القضارف',
                'name_en' => 'Al-Qadarif',
                'state_id' => 3,
                'state_name_ar' => 'ولاية كسلا',
                'state_name_en' => 'Kassala State',
                'latitude' => 14.0347,
                'longitude' => 35.3833,
                'is_major_city' => true,
                'has_airport' => false,
                'has_port' => false,
                'population' => 363945,
                'active' => true
            ],
            [
                'name_ar' => 'ود الحليو',
                'name_en' => 'Wad al-Hilaiw',
                'state_id' => 3,
                'state_name_ar' => 'ولاية كسلا',
                'state_name_en' => 'Kassala State',
                'latitude' => 14.4500,
                'longitude' => 35.7500,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 50000,
                'active' => true
            ],
            [
                'name_ar' => 'خشم القربة',
                'name_en' => 'Khashm al-Qirba',
                'state_id' => 3,
                'state_name_ar' => 'ولاية كسلا',
                'state_name_en' => 'Kassala State',
                'latitude' => 14.9167,
                'longitude' => 35.9333,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 85000,
                'active' => true
            ],

            // Gedaref State (4)
            [
                'name_ar' => 'القضارف',
                'name_en' => 'Gedaref',
                'state_id' => 4,
                'state_name_ar' => 'ولاية القضارف',
                'state_name_en' => 'Gedaref State',
                'latitude' => 14.0347,
                'longitude' => 35.3833,
                'is_major_city' => true,
                'has_airport' => true,
                'has_port' => false,
                'population' => 363945,
                'active' => true
            ],
            [
                'name_ar' => 'الفاو',
                'name_en' => 'Al-Fao',
                'state_id' => 4,
                'state_name_ar' => 'ولاية القضارف',
                'state_name_en' => 'Gedaref State',
                'latitude' => 13.3333,
                'longitude' => 35.2667,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 35000,
                'active' => true
            ],
            [
                'name_ar' => 'الحواتة',
                'name_en' => 'Al-Hawata',
                'state_id' => 4,
                'state_name_ar' => 'ولاية القضارف',
                'state_name_en' => 'Gedaref State',
                'latitude' => 13.8667,
                'longitude' => 35.6667,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 25000,
                'active' => true
            ],

            // River Nile State (5)
            [
                'name_ar' => 'عطبرة',
                'name_en' => 'Atbara',
                'state_id' => 5,
                'state_name_ar' => 'ولاية نهر النيل',
                'state_name_en' => 'River Nile State',
                'latitude' => 17.7022,
                'longitude' => 33.9816,
                'is_major_city' => true,
                'has_airport' => false,
                'has_port' => false,
                'population' => 111399,
                'active' => true
            ],
            [
                'name_ar' => 'الدامر',
                'name_en' => 'Ad-Damir',
                'state_id' => 5,
                'state_name_ar' => 'ولاية نهر النيل',
                'state_name_en' => 'River Nile State',
                'latitude' => 17.5936,
                'longitude' => 33.9608,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 80000,
                'active' => true
            ],
            [
                'name_ar' => 'شندي',
                'name_en' => 'Shendi',
                'state_id' => 5,
                'state_name_ar' => 'ولاية نهر النيل',
                'state_name_en' => 'River Nile State',
                'latitude' => 16.6917,
                'longitude' => 33.4344,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 56000,
                'active' => true
            ],
            [
                'name_ar' => 'المتمة',
                'name_en' => 'Al-Matamma',
                'state_id' => 5,
                'state_name_ar' => 'ولاية نهر النيل',
                'state_name_en' => 'River Nile State',
                'latitude' => 17.6853,
                'longitude' => 33.9397,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 35000,
                'active' => true
            ],
            [
                'name_ar' => 'بربر',
                'name_en' => 'Berber',
                'state_id' => 5,
                'state_name_ar' => 'ولاية نهر النيل',
                'state_name_en' => 'River Nile State',
                'latitude' => 18.0167,
                'longitude' => 33.9833,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 45000,
                'active' => true
            ],

            // Northern State (6)
            [
                'name_ar' => 'دنقلا',
                'name_en' => 'Dongola',
                'state_id' => 6,
                'state_name_ar' => 'ولاية الشمالية',
                'state_name_en' => 'Northern State',
                'latitude' => 19.1808,
                'longitude' => 30.4781,
                'is_major_city' => true,
                'has_airport' => true,
                'has_port' => false,
                'population' => 58735,
                'active' => true
            ],
            [
                'name_ar' => 'كريمة',
                'name_en' => 'Karima',
                'state_id' => 6,
                'state_name_ar' => 'ولاية الشمالية',
                'state_name_en' => 'Northern State',
                'latitude' => 18.5472,
                'longitude' => 31.8506,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 15000,
                'active' => true
            ],
            [
                'name_ar' => 'مروي',
                'name_en' => 'Merowe',
                'state_id' => 6,
                'state_name_ar' => 'ولاية الشمالية',
                'state_name_en' => 'Northern State',
                'latitude' => 18.4739,
                'longitude' => 31.8197,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 45000,
                'active' => true
            ],
            [
                'name_ar' => 'وادي حلفا',
                'name_en' => 'Wadi Halfa',
                'state_id' => 6,
                'state_name_ar' => 'ولاية الشمالية',
                'state_name_en' => 'Northern State',
                'latitude' => 21.8000,
                'longitude' => 31.3500,
                'is_major_city' => false,
                'has_airport' => true,
                'has_port' => false,
                'population' => 15000,
                'active' => true
            ],

            // Gezira State (7)
            [
                'name_ar' => 'ود مدني',
                'name_en' => 'Wad Madani',
                'state_id' => 7,
                'state_name_ar' => 'ولاية الجزيرة',
                'state_name_en' => 'Gezira State',
                'latitude' => 14.4010,
                'longitude' => 33.5197,
                'is_major_city' => true,
                'has_airport' => false,
                'has_port' => false,
                'population' => 345290,
                'active' => true
            ],
            [
                'name_ar' => 'الحصاحيصا',
                'name_en' => 'Al-Hasaheisa',
                'state_id' => 7,
                'state_name_ar' => 'ولاية الجزيرة',
                'state_name_en' => 'Gezira State',
                'latitude' => 14.9000,
                'longitude' => 33.3000,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 85000,
                'active' => true
            ],
            [
                'name_ar' => 'المناقل',
                'name_en' => 'Al-Manaqil',
                'state_id' => 7,
                'state_name_ar' => 'ولاية الجزيرة',
                'state_name_en' => 'Gezira State',
                'latitude' => 14.2500,
                'longitude' => 32.9833,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 60000,
                'active' => true
            ],
            [
                'name_ar' => 'الكاملين',
                'name_en' => 'Al-Kamlin',
                'state_id' => 7,
                'state_name_ar' => 'ولاية الجزيرة',
                'state_name_en' => 'Gezira State',
                'latitude' => 14.0000,
                'longitude' => 33.5000,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 40000,
                'active' => true
            ],

            // White Nile State (8)
            [
                'name_ar' => 'ربك',
                'name_en' => 'Rabak',
                'state_id' => 8,
                'state_name_ar' => 'ولاية النيل الأبيض',
                'state_name_en' => 'White Nile State',
                'latitude' => 13.1833,
                'longitude' => 32.7500,
                'is_major_city' => true,
                'has_airport' => false,
                'has_port' => false,
                'population' => 180000,
                'active' => true
            ],
            [
                'name_ar' => 'كوستي',
                'name_en' => 'Kosti',
                'state_id' => 8,
                'state_name_ar' => 'ولاية النيل الأبيض',
                'state_name_en' => 'White Nile State',
                'latitude' => 13.1650,
                'longitude' => 32.6639,
                'is_major_city' => true,
                'has_airport' => false,
                'has_port' => false,
                'population' => 345000,
                'active' => true
            ],
            [
                'name_ar' => 'الدويم',
                'name_en' => 'Ad-Duwaym',
                'state_id' => 8,
                'state_name_ar' => 'ولاية النيل الأبيض',
                'state_name_en' => 'White Nile State',
                'latitude' => 13.9936,
                'longitude' => 32.3150,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 52638,
                'active' => true
            ],

            // Sennar State (9)
            [
                'name_ar' => 'سنار',
                'name_en' => 'Sennar',
                'state_id' => 9,
                'state_name_ar' => 'ولاية سنار',
                'state_name_en' => 'Sennar State',
                'latitude' => 13.5500,
                'longitude' => 33.5833,
                'is_major_city' => true,
                'has_airport' => false,
                'has_port' => false,
                'population' => 143059,
                'active' => true
            ],
            [
                'name_ar' => 'سنجة',
                'name_en' => 'Sinja',
                'state_id' => 9,
                'state_name_ar' => 'ولاية سنار',
                'state_name_en' => 'Sennar State',
                'latitude' => 13.3500,
                'longitude' => 33.9167,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 55000,
                'active' => true
            ],
            [
                'name_ar' => 'الدندر',
                'name_en' => 'Ad-Damazin',
                'state_id' => 9,
                'state_name_ar' => 'ولاية سنار',
                'state_name_en' => 'Sennar State',
                'latitude' => 11.7833,
                'longitude' => 34.3500,
                'is_major_city' => false,
                'has_airport' => true,
                'has_port' => false,
                'population' => 111984,
                'active' => true
            ],

            // Blue Nile State (10)
            [
                'name_ar' => 'الدمازين',
                'name_en' => 'Ad-Damazin',
                'state_id' => 10,
                'state_name_ar' => 'ولاية النيل الأزرق',
                'state_name_en' => 'Blue Nile State',
                'latitude' => 11.7833,
                'longitude' => 34.3500,
                'is_major_city' => true,
                'has_airport' => true,
                'has_port' => false,
                'population' => 111984,
                'active' => true
            ],
            [
                'name_ar' => 'الروصيرص',
                'name_en' => 'Ar-Rusayris',
                'state_id' => 10,
                'state_name_ar' => 'ولاية النيل الأزرق',
                'state_name_en' => 'Blue Nile State',
                'latitude' => 11.8667,
                'longitude' => 34.3833,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 40000,
                'active' => true
            ],
            [
                'name_ar' => 'الكرمك',
                'name_en' => 'Al-Kurmuk',
                'state_id' => 10,
                'state_name_ar' => 'ولاية النيل الأزرق',
                'state_name_en' => 'Blue Nile State',
                'latitude' => 10.5333,
                'longitude' => 34.2667,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 25000,
                'active' => true
            ],

            // North Kordofan State (11)
            [
                'name_ar' => 'الأبيض',
                'name_en' => 'Al-Ubayyid',
                'state_id' => 11,
                'state_name_ar' => 'ولاية شمال كردفان',
                'state_name_en' => 'North Kordofan State',
                'latitude' => 13.1833,
                'longitude' => 30.2167,
                'is_major_city' => true,
                'has_airport' => true,
                'has_port' => false,
                'population' => 345126,
                'active' => true
            ],
            [
                'name_ar' => 'بارا',
                'name_en' => 'Bara',
                'state_id' => 11,
                'state_name_ar' => 'ولاية شمال كردفان',
                'state_name_en' => 'North Kordofan State',
                'latitude' => 13.6833,
                'longitude' => 30.3833,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 65000,
                'active' => true
            ],
            [
                'name_ar' => 'سودري',
                'name_en' => 'Sodiri',
                'state_id' => 11,
                'state_name_ar' => 'ولاية شمال كردفان',
                'state_name_en' => 'North Kordofan State',
                'latitude' => 13.2833,
                'longitude' => 30.0167,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 30000,
                'active' => true
            ],

            // South Kordofan State (12)
            [
                'name_ar' => 'كادقلي',
                'name_en' => 'Kadugli',
                'state_id' => 12,
                'state_name_ar' => 'ولاية جنوب كردفان',
                'state_name_en' => 'South Kordofan State',
                'latitude' => 11.0000,
                'longitude' => 29.7167,
                'is_major_city' => true,
                'has_airport' => true,
                'has_port' => false,
                'population' => 80000,
                'active' => true
            ],
            [
                'name_ar' => 'الدلنج',
                'name_en' => 'Ad-Dalin',
                'state_id' => 12,
                'state_name_ar' => 'ولاية جنوب كردفان',
                'state_name_en' => 'South Kordofan State',
                'latitude' => 11.9833,
                'longitude' => 29.6500,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 40000,
                'active' => true
            ],
            [
                'name_ar' => 'الأبيض',
                'name_en' => 'Abyei',
                'state_id' => 12,
                'state_name_ar' => 'ولاية جنوب كردفان',
                'state_name_en' => 'South Kordofan State',
                'latitude' => 9.5833,
                'longitude' => 28.4167,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 50000,
                'active' => true
            ],

            // North Darfur State (13)
            [
                'name_ar' => 'الفاشر',
                'name_en' => 'Al-Fashir',
                'state_id' => 13,
                'state_name_ar' => 'ولاية شمال دارفور',
                'state_name_en' => 'North Darfur State',
                'latitude' => 13.6269,
                'longitude' => 25.3494,
                'is_major_city' => true,
                'has_airport' => true,
                'has_port' => false,
                'population' => 264734,
                'active' => true
            ],
            [
                'name_ar' => 'كبكابية',
                'name_en' => 'Kabkabiya',
                'state_id' => 13,
                'state_name_ar' => 'ولاية شمال دارفور',
                'state_name_en' => 'North Darfur State',
                'latitude' => 13.4167,
                'longitude' => 24.1667,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 45000,
                'active' => true
            ],
            [
                'name_ar' => 'الطينة',
                'name_en' => 'At-Tina',
                'state_id' => 13,
                'state_name_ar' => 'ولاية شمال دارفور',
                'state_name_en' => 'North Darfur State',
                'latitude' => 14.2500,
                'longitude' => 24.9167,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 20000,
                'active' => true
            ],
            [
                'name_ar' => 'الكُمّا',
                'name_en' => 'Al-Kuma',
                'state_id' => 13,
                'state_name_ar' => 'ولاية شمال دارفور',
                'state_name_en' => 'North Darfur State',
                'latitude' => 13.5833,
                'longitude' => 24.4000,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 15000,
                'active' => true
            ],

            // South Darfur State (14)
            [
                'name_ar' => 'نيالا',
                'name_en' => 'Nyala',
                'state_id' => 14,
                'state_name_ar' => 'ولاية جنوب دارفور',
                'state_name_en' => 'South Darfur State',
                'latitude' => 12.0500,
                'longitude' => 24.8833,
                'is_major_city' => true,
                'has_airport' => true,
                'has_port' => false,
                'population' => 565734,
                'active' => true
            ],
            [
                'name_ar' => 'كاس',
                'name_en' => 'Kass',
                'state_id' => 14,
                'state_name_ar' => 'ولاية جنوب دارفور',
                'state_name_en' => 'South Darfur State',
                'latitude' => 12.7333,
                'longitude' => 24.0833,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 40000,
                'active' => true
            ],
            [
                'name_ar' => 'الضعين',
                'name_en' => 'Ad-Daein',
                'state_id' => 14,
                'state_name_ar' => 'ولاية جنوب دارفور',
                'state_name_en' => 'South Darfur State',
                'latitude' => 11.4667,
                'longitude' => 26.1167,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 55000,
                'active' => true
            ],

            // West Darfur State (15)
            [
                'name_ar' => 'الجنينة',
                'name_en' => 'Al-Junaynah',
                'state_id' => 15,
                'state_name_ar' => 'ولاية غرب دارفور',
                'state_name_en' => 'West Darfur State',
                'latitude' => 13.4500,
                'longitude' => 22.4500,
                'is_major_city' => true,
                'has_airport' => true,
                'has_port' => false,
                'population' => 150000,
                'active' => true
            ],
            [
                'name_ar' => 'قرضة',
                'name_en' => 'Qurida',
                'state_id' => 15,
                'state_name_ar' => 'ولاية غرب دارفور',
                'state_name_en' => 'West Darfur State',
                'latitude' => 14.1167,
                'longitude' => 22.7167,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 25000,
                'active' => true
            ],

            // East Darfur State (16)
            [
                'name_ar' => 'الضعين',
                'name_en' => 'Ad-Daein',
                'state_id' => 16,
                'state_name_ar' => 'ولاية شرق دارفور',
                'state_name_en' => 'East Darfur State',
                'latitude' => 11.4667,
                'longitude' => 26.1167,
                'is_major_city' => true,
                'has_airport' => false,
                'has_port' => false,
                'population' => 55000,
                'active' => true
            ],
            [
                'name_ar' => 'أبو جابرة',
                'name_en' => 'Abu Jabra',
                'state_id' => 16,
                'state_name_ar' => 'ولاية شرق دارفور',
                'state_name_en' => 'East Darfur State',
                'latitude' => 11.0000,
                'longitude' => 26.5000,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 20000,
                'active' => true
            ],

            // Central Darfur State (17)
            [
                'name_ar' => 'زالنجي',
                'name_en' => 'Zalingei',
                'state_id' => 17,
                'state_name_ar' => 'ولاية وسط دارفور',
                'state_name_en' => 'Central Darfur State',
                'latitude' => 12.9167,
                'longitude' => 23.4667,
                'is_major_city' => true,
                'has_airport' => true,
                'has_port' => false,
                'population' => 80000,
                'active' => true
            ],
            [
                'name_ar' => 'أم دخن',
                'name_en' => 'Um Dukhun',
                'state_id' => 17,
                'state_name_ar' => 'ولاية وسط دارفور',
                'state_name_en' => 'Central Darfur State',
                'latitude' => 11.7833,
                'longitude' => 23.1500,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 30000,
                'active' => true
            ],

            // West Kordofan State (18)
            [
                'name_ar' => 'الفولة',
                'name_en' => 'Al-Fula',
                'state_id' => 18,
                'state_name_ar' => 'ولاية غرب كردفان',
                'state_name_en' => 'West Kordofan State',
                'latitude' => 11.7333,
                'longitude' => 28.4500,
                'is_major_city' => true,
                'has_airport' => false,
                'has_port' => false,
                'population' => 40000,
                'active' => true
            ],
            [
                'name_ar' => 'بابنوسة',
                'name_en' => 'Babanusa',
                'state_id' => 18,
                'state_name_ar' => 'ولاية غرب كردفان',
                'state_name_en' => 'West Kordofan State',
                'latitude' => 11.3333,
                'longitude' => 27.8000,
                'is_major_city' => false,
                'has_airport' => false,
                'has_port' => false,
                'population' => 25000,
                'active' => true
            ],
        ];

        DB::table('sudanese_cities')->insert($cities);
    }
}
